language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t baddu07/docker-react -f Dockerfile.dev .

script: 

  - docker run baddu07/docker-react npm run test -- --coverage

#  - docker run -e CI=true baddu07/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-357665670175"
  bucket_path: "docker"
  on:
    branch: master

  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
